# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	beam = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = false
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	guardian_laser = true

			[light_sources.settings.block_entities.minecraft]
				bed = true
				calibrated_sculk_sensor = true
				furnace = true
				dropper = true
				daylight_detector = true
				sign = true
				jukebox = true
				brewing_stand = true
				sculk_sensor = true
				hanging_sign = true
				brushable_block = true
				conduit = true
				beehive = true
				dispenser = true
				smoker = true
				lectern = true
				skull = true
				campfire = true
				barrel = true
				chest = true
				piston = true
				sculk_shrieker = true
				end_portal = true
				shulker_box = true
				enchanting_table = true
				banner = true
				structure_block = true
				sculk_catalyst = true
				ender_chest = true
				bell = true
				end_gateway = true
				comparator = true
				beacon = true
				command_block = true
				jigsaw = true
				hopper = true
				mob_spawner = true
				chiseled_bookshelf = true
				trapped_chest = true
				decorated_pot = true
				blast_furnace = true

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				pale_oak_boat = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				jungle_chest_boat = true
				mule = true
				bat = true
				husk = true
				camel = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				creaking = true
				item = true
				oak_chest_boat = true
				goat = true
				horse = true
				vindicator = true
				birch_boat = true
				minecart = true
				spectral_arrow = true
				llama_spit = true
				mooshroom = true
				oak_boat = true
				glow_item_frame = false
				snowball = true
				tnt = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				dark_oak_chest_boat = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				zombie = true
				ender_pearl = true
				item_display = true
				breeze_wind_charge = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				zombie_villager = true
				block_display = true
				tnt_minecart = true
				elder_guardian = true
				chest_boat = true
				cherry_chest_boat = true
				acacia_chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				witch = true
				cod = true
				snow_golem = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				birch_chest_boat = true
				magma_cube = true
				pig = true
				skeleton = true
				spruce_boat = true
				frog = true
				hoglin = true
				armadillo = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				shulker = true
				turtle = true
				jungle_boat = true
				salmon = true
				vex = true
				wandering_trader = true
				wither_skeleton = true
				piglin_brute = true
				breeze = true
				ocelot = true
				furnace_minecart = true
				acacia_boat = true
				pale_oak_chest_boat = true
				mangrove_boat = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				sniffer = true
				dark_oak_boat = true
				trader_llama = true
				donkey = true
				bamboo_chest_raft = true
				bogged = true
				bamboo_raft = true
				fox = true
				mangrove_chest_boat = true
				cherry_boat = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				wind_charge = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				ominous_item_spawner = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true
				spruce_chest_boat = true

			[light_sources.settings.entities.gipples_galore]
				gipple = true
				aneuploidian = true

			[light_sources.settings.entities.snuffles]
				snuffle = true

			[light_sources.settings.entities.connectiblechains]
				chain_knot = true
				chain_collision = true

			[light_sources.settings.entities.enderscape]
				rustle = true
				rubblemite = true
				drifter = true
				driftlet = true

			[light_sources.settings.entities.birdsboids]
				bird = true

			[light_sources.settings.entities.animalgarden_owl]
				owl = true

			[light_sources.settings.entities.fishofthieves]
				devilfish = true
				splashtail = true
				stormfish = true
				coconut_chest_boat = true
				ancientscale = true
				wrecker = true
				battlegill = true
				plentifin = true
				wildsplash = true
				islehopper = true
				coconut_boat = true
				pondie = true

			[light_sources.settings.entities.zombifiedplayer]
				zombified_player = true

			[light_sources.settings.entities.smallships]
				ground_cannon = true
				galley = true
				brigg = true
				drakkar = true
				cog = true
				cannon_ball = true

			[light_sources.settings.entities.animalgarden_porcupine]
				porcupine = true

			[light_sources.settings.entities.jagmkiwis]
				kiwi = true
				laser_beam = true

			[light_sources.settings.entities.untitledduckmod]
				duck_egg = true
				duck = true
				goose = true
				goose_egg = true

			[light_sources.settings.entities.ydms_redpanda]
				redpanda = true

			[light_sources.settings.entities.friendsandfoes]
				copper_golem = true
				glare = true
				illusioner = true
				player_illusion = true
				ice_chunk = true
				moobloom = true
				tuff_golem = true
				mauler = true
				iceologer = true
				wildfire = true
				crab = true
				rascal = true

			[light_sources.settings.entities.animalgarden_meerkat]
				meerkat = true

			[light_sources.settings.entities.happy_ghast_legacy]
				happy_ghast = true

			[light_sources.settings.entities.travelersbackpack]
				backpack = true

[debug]
	active_dynamic_lighting_cells = false
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false
