version = 1
enableSodiumMenu = true
dontCull = []
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 20
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 3.4
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = false

[modCompatibility]
copperrails = true
stoneworks = false
enderscape = true
nightlights = false
gipples_galore = true
fishofthieves = true
travelersbackpack = false
beautify = true
waystones = true
easymagic = true
potioncauldron = false
chimes = false
plentyplates = true
snuffles = false
friendsandfoes = true
easyanvils = true
comforts = true
visualworkbench = true
resource_backpacks = true
animal_feeding_trough = true
minecraft = true
wet-sand = true
happy_ghast_legacy = true
